### ISSUE TITLE
White screen issue

### ISSUE THREAD

**Issue by sadikerd** [lauthieb/code-notes#119]
**Describe the bug**
It doesn't work for me!!! i saved all snippets ( i passed 1 hour) then totally white screen. And the repository is not like mentioned earlier.

It is like this;
Windows 7, 8.1, and 10: C:\Users[username]\AppData\Local\Programs\code-notes
I installed version 1.2.3 
Win 10

**Comment by sadikerd** [comment]
I tried to install and uninstall as well, no change.

**Comment by sadikerd** [comment]
I can see only 2 menus Application and Edit

**Comment by lauthieb** [comment]
Okay thanks. I think it's an issue on Windows.
I don't have a Windows computer... Can anyone help me? :(
@kartik-budhiraja @kodaman2 ?

**Comment by lauthieb** [comment]
Sorry for the inconvenience... It's an open source project with a few people and no CI/CD/tests chain :(

**Comment by lauthieb** [comment]
As a workaround, you can reinstall Code Notes 1.2.2 and check notes and settings are in the "userData" directory of this application:
- Windows 7, 8.1, and 10: C:\Users[username]\AppData\Local\code-notes
- Mac OS X El Capitan: Users/[username]/Library/Application Support/code-notes
- Linux: /home/[username]/.config/code-notes

Inside this folder, you will have notes.db and settings.db. So, you would be able to copy/paste those files in another computer.

Sorry again.

**Comment by lauthieb** [comment]
Can anyone could helped by running the application in development with Windows?

**Comment by sadikerd** [comment]
Thanks fast response. Version 1.2.2 works well. And it is the best Snippet tool that I've seen. The simplest is the best all the time. Thanks again for making our life easier bro ;)

**Comment by lauthieb** [comment]
Thanks a lot for these words.
We will try to fix it asap.

When you have time, can you try to clone this project and launch:
- `npm install`
- `npm run dev`
and see what's happening in the developer console?

Thanks a lot in advance.

**Comment by kartik-budhiraja** [comment]
I have a windows, I will test it and let you know. @lauthieb

**Comment by lauthieb** [comment]
Thanks a lot @kartik-budhiraja

**Comment by kodaman2** [comment]
@lauthieb I had built it on Windows 10 on the branch I fixed, tested built and dev. Will have to recheck if anything changed from merging to master or if any new commits changed anything.

**Comment by lauthieb** [comment]
So strange :/

**Comment by lnrdnl** [comment]
I cloned version 1.2.3 last Thursday and I used it the whole day. No issues.

**Comment by lauthieb** [comment]
Thanks @lnrdnl.
Hm. I've no idea... :O

**Comment by lnrdnl** [comment]
Maybe it is also an idea to just add "Open DevTools" in the menu. In my personal projects I used to hide it in prod build, but after some small issues with styling I decided to just make it available in the menu for everyone. A lot of dev tools build with Electron have the option to open Devtools. VSCode for example also has the option to open devtools.

Code-Notes is a tool aiming on developers, so why not just add it to the menu?

**Comment by kodaman2** [comment]
@lnrdnl this is a good idea! :smiley: I think we should also use a log file to log important messages / errors in case user is not familiar with dev tools.

**Comment by sadikerd** [comment]
Both, but generally local.

**Comment by sadikerd** [comment]
When I install, it is opened normally, then I saved all snippets. Then I closed the app.
When I reopen the app, it was trying to load, i have seen loading bar, then all are disappeared. Only top two menus Application and Edit which do not help me to give you a lot information.

**Comment by sadikerd** [comment]
By the way I'm using Win 10 X64.

**Comment by kodaman2** [comment]
Im going to build an exe with developers tools to see if we can get to the bottom of this, I'm running same version you have with no issues on Win10. I wonder if there's some parsing issue going on and that's why it won't render anything.

**Comment by kodaman2** [comment]
@sadikerd if you can build from master please do and add the following line, been really busy this week:

src/main/index.js  just after the new BrowserWindow construction, to force the dev tools to open on launch

```
mainWindow.webContents.openDevTools()
```

Then let us know if you see any errors on the console.

**Comment by Crushedice** [comment]
i kinda found out WHY its happening.  
all else i leave to u 
Made a short clip showing it, better then a wall of text
[http://dmt.ovh/images/webm/bXDc7.webm](url)

Basically, leaving name and desc. empty is unhandled

**Comment by kodaman2** [comment]
@Crushedice Great job! Yes, I am thinking those variables go to null and then the app goes haywire. Should probably make an empty string or disable create button if required values are empty. 

Here's the link, you have it backwards on the markdown btw :wink:

http://dmt.ovh/images/webm/bXDc7.webm

**Comment by kodaman2** [comment]
Btw this behavior does not occur with gists, only with local notes. So if anyone is brave enough I think the best thing to do is to disable create button until note has required boxes filled.

**Comment by kodaman2** [comment]
> I tried to install and uninstall as well, no change.

We should probably also look into why the uninstalling is leaving data behind.

**Comment by kodaman2** [comment]
ToDos from this issue:

- Disable create button on local notes if there are any blank boxes.
- Add Button to enable developer tools
- Could also add console logs to an actual logging file so user can add that to repo issues.
- Investigate why uninstalling is leaving data behind.

**Comment by lauthieb** [comment]
Completely right with this ToDo List.
Thanks guys for this investigation!

**Comment by lauthieb** [comment]
This issue is now fixed thanks to @kodaman2 and its PR #123.
I will let you inform when a new version will be published :)

**Comment by sadikerd** [comment]
The problem with 1.2.4 is still exist for me.
It does't show anything on the screen except white screen.
Little video: https://1drv.ms/v/s!AhakfZB-78XWh1-uAWShXsvAPXSv?e=Hfz4VX

![2020-07-24_11-03-17](https://user-images.githubusercontent.com/18291421/88376341-78e42a80-cd9d-11ea-91ba-fbd13c1cc241.png)

**Comment by sadikerd** [comment]
Windows 10 X64
